export const MODEL_INFO = {
  lstm: {
    fullName: 'LSTM',
    label: '2-layer LSTM · hidden=128 · dropout=0.2',
    bodyText: 'A 2-layer recurrent network (hidden=128, dropout=0.2) learns to map 48 hours of weather features into the next 24 hours of temperature. Adam optimizer, MSE loss, early stopping when validation loss stops improving.',
    midTag: '2× LSTM 128',
    nodeLabels: [['Input','13 features × 48h'],['LSTM 1','128 hidden'],['LSTM 2','128 hidden'],['Output','24h forecast']],
    layers: [
      { count: 13,  x: -9, color: 0xff7a59, radius: 3.2 },
      { count: 128, x: -3, color: 0xffa37a, radius: 4.6 },
      { count: 128, x:  3, color: 0x5fa8ff, radius: 4.6 },
      { count: 24,  x:  9, color: 0xc084fc, radius: 3.4 },
    ],
    recurrent: [1, 2],
    sampleK: [6, 4, 6],
  },
  gru: {
    fullName: 'GRU',
    label: '2-layer GRU · hidden=128 · dropout=0.2',
    bodyText: 'A 2-layer gated recurrent network (hidden=128, dropout=0.2) — like LSTM but with fewer gates. Maps 48 hours of weather features into the next 24 hours of temperature. Adam optimizer, MSE loss, early stopping.',
    midTag: '2× GRU 128',
    nodeLabels: [['Input','13 features × 48h'],['GRU 1','128 hidden'],['GRU 2','128 hidden'],['Output','24h forecast']],
    layers: [
      { count: 13,  x: -9, color: 0xff7a59, radius: 3.2 },
      { count: 128, x: -3, color: 0x6ee7a7, radius: 4.6 },
      { count: 128, x:  3, color: 0x5fa8ff, radius: 4.6 },
      { count: 24,  x:  9, color: 0xc084fc, radius: 3.4 },
    ],
    recurrent: [1, 2],
    sampleK: [6, 4, 6],
  },
  mlp: {
    fullName: 'MLP',
    label: 'MLP · 256 hidden × 2 · dropout=0.2',
    bodyText: 'A flat fully-connected network: the 48h × 13-feature window is flattened into a single 624-dim vector, passed through two ReLU + dropout layers of 256 units, then projected to 24 hourly outputs.',
    midTag: 'Dense 256 × 2',
    nodeLabels: [['Input','13 × 48 = 624'],['Dense 1','256 hidden'],['Dense 2','256 hidden'],['Output','24h forecast']],
    layers: [
      { count: 24,  x: -9, color: 0xff7a59, radius: 3.6 },
      { count: 64,  x: -3, color: 0xffa37a, radius: 4.6 },
      { count: 64,  x:  3, color: 0x5fa8ff, radius: 4.6 },
      { count: 24,  x:  9, color: 0xc084fc, radius: 3.4 },
    ],
    recurrent: [],
    sampleK: [4, 3, 4],
  },
  tcn: {
    fullName: 'TCN',
    label: 'Dilated TCN · 4 layers · 64 channels · dropout=0.2',
    bodyText: 'A stack of 1D convolutions with growing dilation (1, 2, 4, 8). Each layer sees an exponentially wider slice of the input window, capturing both short and long-range patterns without recurrence.',
    midTag: 'TCN 64ch · d=1,2,4,8',
    nodeLabels: [['Input','13 features × 48h'],['Conv d=1,2','64 ch'],['Conv d=4,8','64 ch'],['Output','24h forecast']],
    layers: [
      { count: 13,  x: -9, color: 0xff7a59, radius: 3.2 },
      { count: 64,  x: -3, color: 0xffa37a, radius: 4.6 },
      { count: 64,  x:  3, color: 0xffd866, radius: 4.6 },
      { count: 24,  x:  9, color: 0xc084fc, radius: 3.4 },
    ],
    recurrent: [],
    dilatedArcs: [1, 2],
    sampleK: [5, 3, 5],
  },
  ensemble: {
    fullName: 'Ensemble',
    label: 'Ensemble · mean of LSTM + GRU + MLP + TCN',
    bodyText: 'A simple averaging ensemble: every base model runs on the same input window and their 24h predictions are averaged element-wise. Diverse error patterns cancel out, giving a lower validation RMSE than any single member.',
    midTag: 'mean(LSTM, GRU, MLP, TCN)',
    nodeLabels: [['Input','13 features × 48h'],['Base models','LSTM · GRU · MLP · TCN'],['Mean','element-wise avg'],['Output','24h forecast']],
    layers: [
      { count: 13, x: -9, color: 0xff7a59, radius: 3.2 },
      { count: 4,  x: -3, color: 0xc084fc, radius: 5.4 },
      { count: 1,  x:  3, color: 0xffffff, radius: 6.0 },
      { count: 24, x:  9, color: 0xc084fc, radius: 3.4 },
    ],
    recurrent: [],
    sampleK: [4, 4, 4],
  },
};

export const MODEL_COLORS = {
  lstm: '#ffa37a',
  gru:  '#6ee7a7',
  mlp:  '#9aa8ff',
  tcn:  '#ffd866',
  ensemble: '#c084fc',
};
